# Generated by Django 5.0.1 on 2024-02-09 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imageUrl',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
