# Generated by Django 5.0.1 on 2024-02-09 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_post_imageurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='imageUrl',
        ),
    ]
