# Generated by Django 5.0.1 on 2024-02-11 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_remove_post_likes_likes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Likes',
        ),
    ]
