# Generated by Django 5.0.1 on 2024-02-13 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0011_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes_count',
            field=models.IntegerField(default=0),
        ),
    ]
